#!/usr/bin/env python3
"""For each non-isomorphic digraph G of order n, compute its dichromatic
number and the homotopy type of the clique complex of the dihomomorphism
graph Hom_di(D, G), where D is a chosen source digraph.

Usage
-----
    uv run python -m dicolor.dihom_cycle_analysis <order> [--domain {cycle,arc}]
                                                   [--cycle-order K]
                                                   [--format {org,csv}]

where *order* is an integer between 1 and 6.  The source domain D is
selected with ``--domain``:

* ``cycle`` (default) — directed cycle C_k; use ``--cycle-order K`` to set k
  (defaults to *order*).
* ``arc`` — the single directed arc: two vertices, one directed edge.

Results are written to ``dihom_cycle_analysis_<order>_c<k>.org`` (cycle) or
``dihom_arc_analysis_<order>.org`` (arc) by default.

The digraphs are indexed starting from 0, matching the position in
the digraph6 data files from Brendan McKay's database.  Digons (2-cycles)
are always treated as directed cycles when computing the dichromatic number.

Columns
-------
* **#** — 0-based index of the digraph G.
* **Edges** — number of arcs in G.
* **chi_d** — dichromatic number of G (digons counted as cycles).
* **Homotopy type of CC(Hom(D, G))** — homotopy type of the clique complex
  of the undirected dihomomorphism graph from D to G.  Reported as "empty"
  when no dihomomorphism exists.
"""

from __future__ import annotations

import argparse
import csv
import signal
import sys
from contextlib import contextmanager

import networkx as nx

from pycombtop.homotopy_type import homotopy_type_with_verdict

from .digraph_utils import digraph_generator
from .digraph_analysis import dichromatic_number
from .dihomomorphisms import dihomomorphism_graph

# Seconds allowed for the homotopy computation of a single graph.
_HOMOTOPY_TIMEOUT = 120


class _TimeoutError(Exception):
    pass


@contextmanager
def _time_limit(seconds: int):
    """Raise _TimeoutError if the block takes longer than *seconds*."""

    def _handler(signum, frame):
        raise _TimeoutError()

    old = signal.signal(signal.SIGALRM, _handler)
    signal.alarm(seconds)
    try:
        yield
    finally:
        signal.alarm(0)
        signal.signal(signal.SIGALRM, old)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _directed_cycle(n: int) -> nx.DiGraph:
    """Return the directed n-cycle with vertices 0, 1, ..., n-1."""
    C: nx.DiGraph = nx.DiGraph()
    C.add_nodes_from(range(n))
    C.add_edges_from((i, (i + 1) % n) for i in range(n))
    return C


def _single_arc() -> nx.DiGraph:
    """Return the digraph with two vertices and one directed edge 0→1."""
    A: nx.DiGraph = nx.DiGraph()
    A.add_nodes_from([0, 1])
    A.add_edge(0, 1)
    return A


def _homotopy_str(verdict) -> str:
    """Return a plain-text representation of a homotopy verdict."""
    ht = verdict.verdict
    if not verdict.is_exact:
        ht += " [approx]"
    return ht


def _row(
    G: nx.DiGraph,
    Cn: nx.DiGraph,
) -> tuple[int, int, str]:
    """Return ``(edges, chi_d, homotopy_type_string)`` for digraph *G*."""
    chi_d = dichromatic_number(G, allow_digons=False)
    H = dihomomorphism_graph(Cn, G)
    if H.number_of_nodes() == 0:
        return G.number_of_edges(), chi_d, "empty"
    try:
        with _time_limit(_HOMOTOPY_TIMEOUT):
            ht = _homotopy_str(homotopy_type_with_verdict(H))
    except _TimeoutError:
        ht = f"timeout (>{_HOMOTOPY_TIMEOUT}s, V={H.number_of_nodes()}, E={H.number_of_edges()})"
    return G.number_of_edges(), chi_d, ht


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

_ORG_HLINE = "|---+-------+-------+--------------------------------|"


def _write_org_table(
    n: int,
    domain_label: str,
    domain_desc: str,
    rows: list[tuple[int, int, int, str]],
    output_file: str,
) -> None:
    """Write an org-mode table to *output_file*."""
    header = f"| # | Edges | chi_d | Homotopy type of CC(Hom({domain_label},G)) |"
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(f"#+TITLE: Dihomomorphism analysis for order {n} (source {domain_label})\n")
        f.write("#+AUTHOR: Generated by dihom_cycle_analysis.py\n\n")
        f.write(f"Source graph: {domain_desc}\n\n")
        f.write(f"{header}\n")
        f.write(f"{_ORG_HLINE}\n")
        for idx, edges, chi_d, ht in rows:
            f.write(f"| {idx} | {edges} | {chi_d} | {ht} |\n")


def _write_csv(
    n: int,
    domain_label: str,
    rows: list[tuple[int, int, int, str]],
    output_file: str,
) -> None:
    """Write results as a CSV file to *output_file*."""
    with open(output_file, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["#", "edges", "chi_d", f"ht_cc_hom_{domain_label}_g"])
        writer.writerows(rows)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Compute dichromatic number and homotopy type of the clique "
            "complex of Hom_di(C_n, G) for each non-isomorphic digraph G "
            "of order n."
        )
    )
    parser.add_argument(
        "order",
        type=int,
        help="Number of vertices n.  Available: 1 to 6.",
    )
    parser.add_argument(
        "--domain",
        choices=["cycle", "arc"],
        default="cycle",
        help="Source domain digraph: 'cycle' (directed cycle, default) or 'arc' (single directed edge).",
    )
    parser.add_argument(
        "--cycle-order",
        type=int,
        metavar="K",
        default=None,
        help="Length k of the source directed cycle C_k (default: same as order). Only used with --domain cycle.",
    )
    parser.add_argument(
        "--format",
        choices=["csv", "org"],
        default="org",
        help="Output format (default: org).",
    )
    parser.add_argument(
        "--out",
        metavar="FILE",
        help="Output file (default: dihom_cycle_analysis_<order>_c<k>.<fmt> or dihom_arc_analysis_<order>.<fmt>).",
    )
    args = parser.parse_args()

    n = args.order
    fmt = args.format

    if args.domain == "arc":
        domain_graph = _single_arc()
        domain_label = "A"
        domain_desc = "single directed arc (0→1)"
        output_file = args.out or f"dihom_arc_analysis_{n}.{fmt}"
    else:
        k = args.cycle_order if args.cycle_order is not None else n
        domain_graph = _directed_cycle(k)
        domain_label = f"C_{k}"
        domain_desc = f"directed {k}-cycle C_{k}"
        output_file = args.out or f"dihom_cycle_analysis_{n}_c{k}.{fmt}"

    if n >= 5:
        print(
            f"Warning: order {n} has many digraphs; computation may be slow.",
            flush=True,
        )

    print(
        f"Processing digraphs of order {n} "
        f"(source: {domain_desc})...",
        flush=True,
    )

    rows: list[tuple[int, int, int, str]] = []
    for idx, G in enumerate(digraph_generator(n)):
        edges, chi_d, ht = _row(G, domain_graph)
        rows.append((idx, edges, chi_d, ht))

        if idx > 0 and idx % 100 == 0:
            print(f"  {idx} digraphs processed...", flush=True)

    if fmt == "csv":
        _write_csv(n, domain_label, rows, output_file)
    else:
        _write_org_table(n, domain_label, domain_desc, rows, output_file)
    print(f"Done. {len(rows)} digraphs written to: {output_file}")


if __name__ == "__main__":
    sys.exit(main())
